"use client"

import { useEffect, useState } from "react"
import { Bell, Check, Trash2 } from "lucide-react"
import { AppShell } from "@/components/skillsync/shell"
import { notifications as seed } from "@/lib/skillsync/data"

export default function NotificationsPage() {
  const [items, setItems] = useState(seed)
  useEffect(() => { const stored = window.localStorage.getItem("skillsync-notifications"); if (stored) setItems(JSON.parse(stored)) }, [])
  const persist = (next: typeof items) => { setItems(next); window.localStorage.setItem("skillsync-notifications", JSON.stringify(next)) }
  return <AppShell><div className="mx-auto max-w-4xl px-5 py-8 pb-28 sm:px-8 lg:py-10 lg:pb-10"><div className="flex items-end justify-between gap-4"><div><p className="text-sm text-lime-200">Stay in the loop</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em]">Notifications</h1><p className="mt-3 text-sm text-white/45">Updates from your applications, learning, and network.</p></div><button onClick={() => persist(items.map((item) => ({ ...item, unread: false })))} className="rounded-xl border border-white/10 px-3 py-2 text-xs text-white/55 hover:bg-white/[0.06]">Mark all read</button></div><div className="mt-8 flex flex-col gap-3">{items.length ? items.map((item) => <article key={item.id} className={`flex items-start gap-4 rounded-2xl border p-4 transition ${item.unread ? "border-lime-200/20 bg-lime-300/[0.06]" : "border-white/10 bg-white/[0.03]"}`}><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-violet-300/10 text-violet-200"><Bell className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-sm text-white/45">{item.body}</p></div><button onClick={() => persist(items.filter((entry) => entry.id !== item.id))} aria-label={`Delete ${item.title}`} className="text-white/30 hover:text-white"><Trash2 className="size-4" /></button></div><div className="mt-3 flex items-center gap-3 text-xs text-white/30"><span>{item.time}</span>{item.unread && <button onClick={() => persist(items.map((entry) => entry.id === item.id ? { ...entry, unread: false } : entry))} className="inline-flex items-center gap-1 text-lime-200"><Check className="size-3" /> Mark read</button>}</div></div></article>) : <div className="rounded-3xl border border-dashed border-white/15 p-12 text-center"><Bell className="mx-auto size-8 text-white/25" /><p className="mt-4 font-medium">You&apos;re all caught up</p><p className="mt-2 text-sm text-white/40">New application and learning updates will appear here.</p></div>}</div></div></AppShell>
}
